name: Build HotelAdmin Lambda

on:
  push:
    paths:
      - 'HotelAdmin/**'   # trigger only when this folder changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Build ONLY HotelAdmin project
    - name: Build HotelAdmin Lambda
      run: |
        cd HotelAdmin
        dotnet restore
        cd HotelMan_HotelAdmin
        dotnet tool install -g Amazon.Lambda.Tools
        dotnet lambda package --configuration release .\HotelMan_HotelAdmin.csproj -o "./publish/hoteladmin-lambda-v${{ github.run_number }}.zip"

    # Configure AWS
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Upload artifact to S3
    - name: Upload to S3
      run: |
        aws s3 cp ./HotelAdmin/HotelMan_HotelAdmin/publish/hoteladmin-lambda-v${{ github.run_number }}.zip s3://hotel-app-lambda-artifacts-bucket/lambda/hoteladmin-lambda-v${{ github.run_number }}.zip

    - name: Trigger Terraform Deployment
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/vsmross/infra/actions/workflows/deploy.yml/dispatches \
          -d '{
            "ref": "main",
            "inputs": {
              "s3_key": "lambda/hoteladmin-v${{ github.run_number }}.zip"
            }
          }'

    # terraform trigger    
    - name: Trigger Terraform Deployment
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/vsmross/infra/actions/workflows/deploy.yml/dispatches \
          -d '{
            "ref": "main",
            "inputs": {
              "s3_key": "lambda/hoteladmin-v${{ github.run_number }}.zip"
            }
          }'
