name: Build HotelAdmin Lambda

on:
  push:
    paths:
      - 'HotelAdmin/**'   # trigger only when this folder changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    # Build ONLY HotelAdmin project
    - name: Build HotelAdmin Lambda
      run: |
        cd HotelAdmin
        ls -l
        dotnet restore
        cd HotelMan_HotelAdmin
        ls -l
        dotnet tool install -g Amazon.Lambda.Tools
        dotnet lambda package --configuration release .\HotelMan_HotelAdmin.csproj -o "./publish/hoteladmin-lambda.zip"
    # Zip only HotelAdmin output
    - name: Create ZIP
      run: |
        cd HotelAdmin/HotelMan_HotelAdmin/publish
        zip -r ../../hoteladmin-lambda.zip .

    # Configure AWS
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    # Upload artifact to S3
    - name: Upload to S3
      run: |
        aws s3 cp hoteladmin-lambda.zip s3://hotel-lambda-artifacts-bucket/lambda/hoteladmin-lambda.zip
